// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmfeidkkrkbdoiohkook.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptZmVpZGtrcmtiZG9pb2hrb29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NzQ5NjYsImV4cCI6MjA2NjE1MDk2Nn0.0Q-I-4mw1jpfbt-LNOpnO9tC4kjOHZhtaqAjljxIVIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);